version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 7
    groups:
      monthly-npm-updates:
        applies-to: 'version-updates'
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 7
    groups:
      monthly-actions-updates:
        applies-to: 'version-updates'
        patterns:
          - '*'
