name: 'Setup Java JDK'
description: 'Set up a specific version of the Java JDK and add the
   command-line tools to the PATH'
author: 'GitHub'
inputs:
  java-version:
    description: 'The Java version to make available on the path. Takes a whole
       or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x)'
    required: true
  java-package:
    description: 'The package type (jre, jdk, jdk+fx)'
    required: false
    default: 'jdk'
  architecture:
    description: 'The architecture (x86, x64) of the package.'
    required: false
    default: 'x64'
  jdkFile:
    description: 'Path to where the compressed JDK is located. The path could
       be in your source repository or a local path on the agent.'
    required: false
  server-id:
    description: 'ID of the distributionManagement repository in the pom.xml
       file. Default is `github`'
    required: false
  server-username:
    description: 'Environment variable name for the username for authentication
       to the Apache Maven repository. Default is $GITHUB_ACTOR'
    required: false
  server-password:
    description: 'Environment variable name for password or token for
       authentication to the Apache Maven repository. Default is $GITHUB_TOKEN'
    required: false
  settings-path:
    description: 'Path to where the settings.xml file will be written. Default is ~/.m2.'
    required: false
  maven-version:
    description: 'The Maven version to make available on the path. Takes a whole
       or semver Maven version, or 3.x syntax (e.g. 3.6 => Maven 3.x)'
    required: false
  maven-file:
    description: 'Path to where the compressed Maven is located. The path could
       be in your source repository or a local path on the agent.'
    required: false
  maven-mirror:
    description: 'Uri hosting Maven3 mirror packages.'
    required: false
    default: 'https://archive.apache.org/dist/maven/maven-3/'
  gradle-version:
    description: 'The Gradle version to make available on the path. Takes a whole
       or semver Gradle version, or 6.x syntax (e.g. 6.0 => Gradle 6.x)'
    required: false
  gradle-file:
    description: 'Path to where the compressed Gradle is located. The path could
       be in your source repository or a local path on the agent.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
