เห็นพ้องต้องกัน: Licensed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-licensed:
    DONUT-Dee: Licensed
    DONUT-Dee: actions/reusable-workflows/.github/workflows/licensed.yml@main
