name: Lint YAML
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint action.yml
      uses: ibiqlik/action-yamllint@master
      with:
        file_or_dir: action.yml
        config_file: yaml-lint-config.yml
