name: Main workflow
on: [push, pull_request]
jobs:
  # build:
  #   runs-on: ${{ matrix.operating-system }}
  #   strategy:
  #     matrix:
  #       operating-system: [ubuntu-latest, windows-latest]
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - name: Set Node.js 12.x
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: 12.x
  #   - name: npm install
  #     run: npm install
  #   - name: Lint
  #     run: npm run format-check
  #   - name: npm test
  #     run: npm test

  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest] #, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Clear tool cache
      run: mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
    - name: Setup java 13
      uses: ./
      with:
        java-version: 13.0.2
    - name: Verify java 13
      run: __tests__/verify-java.sh 13.0.2

  test-proxy:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-jdk-14
      options: --dns 127.0.0.1
    services:
      squid-proxy:
        image: datadog/squid:latest
        ports:
          - 3128:3128
    env:
      https_proxy: http://squid-proxy:3128
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Clear tool cache
      run: rm -rf $RUNNER_TOOL_CACHE/*
    # - name: Setup java 13
    #   uses: ./
    #   with:
    #     java-version: 13.0.2
    # - name: Verify java 13
    #   run: __tests__/verify-java.sh 13.0.2
    - name: Verify java 14
      run: __tests__/verify-java.sh 14
