name: Main workflow
on: [push, pull_request]
jobs:
  # build:
  #   runs-on: ${{ matrix.operating-system }}
  #   strategy:
  #     matrix:
  #       operating-system: [ubuntu-latest, windows-latest]
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - name: Set Node.js 12.x
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: 12.x
  #   - name: npm install
  #     run: npm install
  #   - name: Lint
  #     run: npm run format-check
  #   - name: npm test
  #     run: npm test

  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest] #, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Clear tool cache
      run: mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
    - run: |
        printenv|sort
    # - name: Clear local maven repository
    #   run: mv "~/.m2/repository" "~/.m2/repository.bak" && mkdir ~/.m2/repository
    - name: Setup java 7
      uses: ./
      with:
        java-version: 7.0.242
    - name: Verify java 7
      run: __tests__/verify-java.sh
    - run: |
        which java
        java -version
    - run: |
        printenv|sort